apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kyt2rhmk4-java-springboot 
  janus-idp.io/tekton: kyt2rhmk4-java-springboot
  backstage.io/kubernetes-id: kyt2rhmk4-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kyt2rhmk4-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml